### ISSUE TITLE
Markdown bullets in comments without a space prefix are incorrectly synchronized

### ISSUE THREAD

**Issue by LukeSwart** [org-trello/org-trello#276] opened 2015-07-13 10:41 UTC
If someone creates a markdown bullet on a card using the syntax "* " instead of the proper syntax " * ", `org-trello` incorrectly imports the card. The "* " is recognized as a new tree instead of as a bullet within a card. 

For example, if someone creates a card with this "slightly improper" bullet, it should be rendered as follows:

```
* TODO Meeting with Joe Blow
DEADLINE: <2015-07-16T18:00:00.000Z>
:PROPERTIES:
:orgtrello-id: 5524235892357298
:orgtrello-local-checksum: 234892745892375289
:END:
  Joe Blow wants to meet

** COMMENT Jane Dow, 2015-07-12T21:41:44.015Z
:PROPERTIES:
:orgtrello-id: 55a2df1861ebf6ca30d4b8f0
:orgtrello-local-checksum: 57eddd7332a5b28e334d1362685beac6ef84afb6665ee6c55e4c0ab56e415703
:END:
 * we are going to meet over the phone. This bullet is "improper"
 * this bullet is proper

* Done New proposal
:PROPERTIES:
:orgtrello-id: 342345235
:orgtrello-local-checksum: wer238729384723948
:END:
```
This is how it should be imported, shown above. Note the user originally typed their card comment bullet with no space prefix, as follows: `* we are going to meet over the phone. This bullet is "improper"`

But, with the current imports, `org-trello` imports it like so:

```
* TODO Meeting with Joe Blow
DEADLINE: <2015-07-16T18:00:00.000Z>
:PROPERTIES:
:orgtrello-id: 5524235892357298
:orgtrello-local-checksum: 234892745892375289
:END:
  Joe Blow wants to meet

** COMMENT Jane Dow, 2015-07-12T21:41:44.015Z
:PROPERTIES:
:orgtrello-id: 55a2df1861ebf6ca30d4b8f0
:orgtrello-local-checksum: 57eddd7332a5b28e334d1362685beac6ef84afb6665ee6c55e4c0ab56e415703
:END:
 * this bullet is proper

* Done New proposal
:PROPERTIES:
:orgtrello-id: 342345235
:orgtrello-local-checksum: wer238729384723948
:END:

* we are going to meet over the phone. This bullet is "improper"
```

The bullet, `* we are going to meet over the phone. This bullet is "improper"`, is appended at the end! It appears to have been treated like a new tree in the root location. This makes for a very confusing import. 

Although the user did not enter proper markdown, Trello is still able to correctly render the bullets, so I think `org-trello` should import them as bullets as well. Possibly all strings that start with "* " can be prefixed with a space? Like "* " -> " * "?

**Comment by ardumont** [comment] 2015-07-13 15:05
> If someone creates a markdown bullet on a card using the syntax...
>  [...]

Nice catch!

> Possibly all strings that start with "* " can be prefixed with a space? Like "* " -> " * "?

This seems reasonable indeed.

Thanks for raising this up.

Cheers,

**Comment by ardumont** [comment] 2015-07-13 16:35
Something along those lines should do (I use 2 spaces):

```lisp
(defun orgtrello-buffer/--prepare-comment (comment)
  "Prepare COMMENT string for writing on disk.
This to avoid clash conflict between `org-mode' and markdown syntax."
  (->> (s-split "\n" comment)
       (-map (-rpartial #'s-append "  "))
       (s-join "\n")))

(defun orgtrello-buffer/--serialize-comment (comment)
  "Serialize COMMENT as string."
  (let* ((comment-user (orgtrello-data/entity-comment-user comment))
         (comment-date (orgtrello-data/entity-comment-date comment))
         (comment-string (orgtrello-data/entity-comment-text comment))
         (comment-id (orgtrello-data/entity-comment-id comment))
         (prepared-comment-str (orgtrello-buffer/--prepare-comment comment-string)))
    (format "\n** COMMENT %s, %s\n:PROPERTIES:\n:orgtrello-id: %s\n:END:\n%s\n" comment-user comment-date comment-id prepared-comment-str)))
```

Cheers,

**Comment by LukeSwart** [comment] 2015-07-13 19:21
Thanks for the quick support! But I am having trouble getting this to work.

I pasted those functions into my `~/.emacs/init.el` file, and when I attempt to sync my buffer from the Trello board via `C-u M-x org-trello-sync-buffer`, it fails and the `*Messages*` buffer outputs the following:

```
org-trello - Request 'sync org buffer from trello board'...
Loading /home/lucas/.emacs.d/.trello/lukeswart.el (source)...done
org-trello - Synchronizing the trello board 'HaxGeo' to the org-mode file...
org-trello - Computing card 'My first card' data...
org-trello - Computing card 'My second card' data...
org-trello - Computing card 'My third card' data...
... (Prints this message for all of my cards)
org-trello - Synchronizing entity 'My first card' with id '5564b696fe12c808c9549a4e'...

org-trello - Sync buffer from trello - Catch error: (void-function -rpartial)
```

where all cards are deleted except the first card, and no comments are imported. Any suggestions? It appears to crash when syncing comments, specifically at the function `rpartial`. Is there a syntax error with the way `rpartial` is called, or am I missing something?

**Comment by LukeSwart** [comment] 2015-07-13 19:30
Assuming that `(-rpartial #'s-append "  ")` was a typo for `(-partial #'s-append "  ")`, I made that change and trello is syncing without error, but the bullets are still imported incorrectly. It doesn't seem to have fixed anything...

**Comment by LukeSwart** [comment] 2015-07-13 19:45
I did some quick debugging by adding `(message "preparing comment: %s" prepared-comment-str)` into the `serialize-comment` function as follows:

```
(defun orgtrello-buffer/--serialize-comment (comment)
  "Serialize COMMENT as string."
  (let* ((comment-user (orgtrello-data/entity-comment-user comment))
         (comment-date (orgtrello-data/entity-comment-date comment))
         (comment-string (orgtrello-data/entity-comment-text comment))
         (comment-id (orgtrello-data/entity-comment-id comment))
         (prepared-comment-str (orgtrello-buffer/--prepare-comment comment-string)))
    (message "preparing comment: %s" prepared-comment-str)
    (format "\n** COMMENT %s, %s\n:PROPERTIES:\n:orgtrello-id: %s\n:END:\n%s\n" comment-user comment-date comment-id prepared-comment-str)))
```

And the `prepared-comment-str` doesn't appear to have any "  " prefix. Running `C-h f #'s-append` doesn't recognize the `#'s-append` function, which may explain why the comments are not getting a "  " appended to them. Any suggestions would be appreciated.

**Comment by ardumont** [comment] 2015-07-14 10:40
Hello.

> But I am having trouble getting this to work.

My bad.
I did just copy/paste you some code without explanation...

I do not want you to install it permanently on your local install (this could unravel some curious behavior if people starting doing that... Behavior that I would not have time to reproduce, understand and fix that is).

For `-rpartial` to be ok, you need to install `dash-functional` (new dependency on org-trello).

The full snippet that will be ok (assuming you have the latest org-trello with this dependency...)

```lisp
(require 'dash-functional)

(defun orgtrello-buffer/--prepare-comment (comment)
  "Prepare COMMENT string for writing on disk.
This to avoid clash conflict between `org-mode' and markdown syntax."
  (->> (s-split "\n" comment)
       (-map (-rpartial #'s-append "  "))
       (s-join "\n")))

(defun orgtrello-buffer/--serialize-comment (comment)
  "Serialize COMMENT as string."
  (let* ((comment-user (orgtrello-data/entity-comment-user comment))
         (comment-date (orgtrello-data/entity-comment-date comment))
         (comment-string (orgtrello-data/entity-comment-text comment))
         (comment-id (orgtrello-data/entity-comment-id comment))
         (prepared-comment-str (orgtrello-buffer/--prepare-comment comment-string)))
    (format "\n** COMMENT %s, %s\n:PROPERTIES:\n:orgtrello-id: %s\n:END:\n%s\n" comment-user comment-date comment-id prepared-comment-str)))
```
*Note* if you do not have dash-functional, just <kbd>M-x package-install RET dash-functional RET</kbd>

I just want you to monkey patch your current install (at next emacs reboot, org-trello will be the normal one) to try and test on your side. I intend to fix this bad behavior in a new version.

Copy/paste this in a *scratch* buffer, then <kbd>M-x eval-buffer</kbd>.
Now check again to sync from trello and everything should be ok.

Cheers,

**Comment by LukeSwart** [comment] 2015-07-15 00:18
Yep, this works. Thanks for fixing this, and for clarifying the solution :-)

**Comment by ardumont** [comment] 2015-07-15 08:35
Hello,

> Yep, this works. 

Cool :D

> Thanks for fixing this, and for clarifying the solution :-)

No problem

I do not close it yet since it's not released but thanks for the vote of confidence :P 

Cheers,

**Comment by LukeSwart** [comment] 2015-07-15 09:48
:+1:

**Closed** 2015-08-05 20:44 UTC
Labels: bug, Fixed, next-release

**Comment by Tambura** [comment] 2022-01-08 14:08
`rpartial` issue appears again:
```
Debugger entered--Lisp error: (void-function -rpartial)
  -rpartial(funcall nil)
  orgtrello-action--execute-controls((orgtrello-controller-migrate-user-setup orgtrello-controller-migrate-user-buffer orgtrello-controller-set-account orgtrello-controller-load-keys orgtrello-controller-control-keys orgtrello-controller-setup-properties))
  orgtrello-action-controls-or-actions-then-do((orgtrello-controller-migrate-user-setup orgtrello-controller-migrate-user-buffer orgtrello-controller-set-account orgtrello-controller-load-keys orgtrello-controller-control-keys orgtrello-controller-setup-properties) orgtrello-controller-do-install-board-and-lists nil)
  orgtrello-action-msg-controls-or-actions-then-do("Install boards and lists" (orgtrello-controller-migrate-user-setup orgtrello-controller-migrate-user-buffer orgtrello-controller-set-account orgtrello-controller-load-keys orgtrello-controller-control-keys orgtrello-controller-setup-properties) orgtrello-controller-do-install-board-and-lists)
  org-trello-log-light-checks-and-do("Install boards and lists" orgtrello-controller-do-install-board-and-lists)
  apply(org-trello-log-light-checks-and-do ("Install boards and lists" orgtrello-controller-do-install-board-and-lists))
  org-trello--apply-deferred-with-quit((org-trello-log-light-checks-and-do "Install boards and lists" orgtrello-controller-do-install-board-and-lists))
  org-trello--apply-deferred((org-trello-log-light-checks-and-do "Install boards and lists" orgtrello-controller-do-install-board-and-lists))
  org-trello-install-board-metadata()
  funcall-interactively(org-trello-install-board-metadata)
  call-interactively(org-trello-install-board-metadata record nil)
  command-execute(org-trello-install-board-metadata record)
  execute-extended-command(nil "org-trello-install-board-metadata" "org-trello-install-board-metadata")
  funcall-interactively(execute-extended-command nil "org-trello-install-board-metadata" "org-trello-install-board-metadata")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command
```

`dash-functional` is deprecated now.

Emacs version: 27.2  (build 1, x86_64-w64-mingw32)
