### ISSUE TITLE
Sync from trello board only fetches one task before throwing an exception

### ISSUE THREAD

**Issue by dmeidlin** [org-trello/org-trello#375] opened 2018-01-20 00:02 UTC
I seem to be having similar problems as others.

I have tried the solutions that have worked for them, but nothing has worked, yet.

I would really appreciate any help or advice. Thanks!

Here is my system.
### M-x org-trello-bug-report

```
System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 26.0.50 (build 1, x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G31))
 of 2017-03-28
- org version: 9.1.6
- org-trello version: 0.8.0
- org-trello path: /Users/<ME>/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

I seem to have set the header correctly in my org file.

```
:PROPERTIES:
#+PROPERTY: board-name <FU-BOARD>
#+PROPERTY: board-id XXXXXXXXXXXXXXXXXXXXXXXX
#+PROPERTY: Release 59cbc951350584eb1053f11f
#+PROPERTY: Validate-Done 590752eec8aeab52fd591889
#+PROPERTY: Validate-Active 590752d75ce18b4bd845a20a
#+PROPERTY: Implement-Done 590752c8643560545dae3850
#+PROPERTY: Implement-Active 590752c1a70811683d0c03d0
#+PROPERTY: Specify 590752aa54e680ab715851fe
#+PROPERTY: Backlog 59075281c75e7004fd0e09df
#+TODO: Backlog Specify Implement-Active Implement-Done Validate-Active Validate-Done Release
#+PROPERTY: orgtrello-user-<BARNEY> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<RUBBLE> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<HOMER> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<SIMPSON> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<BOB> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<BURGER> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<ALEXANDER> ed696dad20af93936b559a5c 
#+PROPERTY: orgtrello-user-<BELL> ed696dad20af93936b559a5c 
#+PROPERTY: :purple <BAR>
#+PROPERTY: :blue Testing
#+PROPERTY: :red Merlin
#+PROPERTY: :pink Content
#+PROPERTY: :green Design
#+PROPERTY: :orange App Dev
#+PROPERTY: :yellow DevOps
#+PROPERTY: :sky CMS+Data
#+PROPERTY: orgtrello-user-me <BAZ>
:END:
```

I issued the command to fetch teh tasks from trello and expected a list of org TODO headings: one for each trello card
C-u C-c o s
org-trello-sync-buffer

### Actual behavior
Only the first card was listed as a heading and the following exception was thrown:
```
org-trello - Request ’sync org buffer from trello board’...
Loading /Users/<ME>/.emacs.d/.trello/<ME-AGAIN>.el (source)...done
org-trello - Sync trello board ’<FU-BOARD>’ to buffer ’FU_BOARD.org’... FAILED. Error: (invalid-function ((symbol-value --cl-buffer-name--)))
```
Let me know if you need any more info. Thanks!

**Comment by gariepyalex** [comment] 2018-02-01 16:05
I have a similar behaviour but in my, case,  the error is:
```
org-trello - Sync trello board ’Foo’ to buffer ’bar.trello’... FAILED. Error: (error "Match data clobbered by buffer modification hooks")
```

**Comment by ardumont** [comment] 2018-03-07 08:09
Hello,

Have you tried the solution mentioned?

In any case, it seems you are missing some cl function.
Possibly, emacs 26 no longer ships the cl `namespace` (common-lisp-like functions) the way it did in prior version...

On the side note, `/Users//.emacs.d/.trello/.el`, you seem to have not defined a user name (or did you scrambled the log?)

Does `M-x org-trello-check-setup` returns ok?

**Comment by ardumont** [comment] 2020-05-10 08:22
Closing issue. I cannot debug issues i cannot reproduce without feedback. No
answer from years now.

The absence of functions is often either installation problems of the package
[1] or the way the user does the installation [2].

The best way to troubleshoot is to reinstall and provides the installation logs
from the `*Message*` buffer (if the problem persists that is).

Feel free to reopen.

[1] https://github.com/org-trello/org-trello/issues?q=label%3Apackage-problem+is%3Aclosed

[2] https://github.com/org-trello/org-trello/issues?q=label%3Asetup-problem+is%3Aclosed

Cheers,

**Closed by ardumont** 2020-05-10 08:22 UTC
Labels: potential-packaging-problem, potential-setup-problem
