### ISSUE TITLE
Unable to get initial set up to work

### ISSUE THREAD

**Issue by ocharles** [org-trello/org-trello#314] opened 2016-02-11 12:28 UTC
I am a spacemacs user, and I used this layer to install `org-trello`: https://github.com/axyz/dotfiles/blob/master/.my-spacemacs-layers/trello/packages.el.

I do have all the `org-trello` commands available in my `.org` file, and `org-trello-bug-report` states:

```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.29)
 of 2016-01-19 on localhost
- org version: 8.2.10
- org-trello version: 0.7.5
- org-trello path: /home/ollie/.emacs.d/elpa/org-trello-20160206.2342/org-trello.el
```

`org-trello/install-key-and-token` launches Firefox, and I'm able to go through the process of getting an app key and an access token. Both of these are present in `~/.emacs.d/.trello/.el`. However, when I run `org-trello/install-board-metadata`, I get:

```
org-trello - Install boards and lists...
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token
```

`org-trello/check-setup` reports:

```
org-trello - Configuration for user '' already existing (file '/home/ollie/.emacs.d/.trello/.el'), skipping.
org-trello - Checking setup.
org-trello - Checking setup....
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token
- Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello-install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)

org-trello - Checking setup. DONE.
```

**Comment by ardumont** [comment] 2016-02-11 13:04
Hello,

It seems to be you, [isn't it](https://trello.com/ocharles)?
I'll assume so for the remaining answer (your current github avatar and login matches).
Feel free to correct me.

> I am a spacemacs user, and I used this layer to install org-trello: https://github.com/axyz/dotfiles/blob/master/.my-spacemacs-layers/trello/packages.el.

Ok.
This is interesting.

Ok, I'm not sure to understand all the details.
What i understand is that it installs org-trello through melpa (via use-package) and add some decorator function around org-trello's).

And you have some internal hook on org to determine if org-trello needs to be launched.

> I do have all the org-trello commands available in my .org file, 

So it works!

> and org-trello-bug-report states:
> System information: ...

Ok, thanks.

> org-trello/install-key-and-token launches Firefox, and I'm able to go through the process of getting an app key and an access token. Both of these are present in ~/.emacs.d/.trello/.el. 

Mmm, here it should be the trello login you used, for example ~/.emacs.d/.trello/ocharles.el.

(there must be a problem during input if it accepts empty values...)

> `org-trello - Configuration for user ''`

This is a consistent error with the previous sample.

The remaining sample show that some function seems to be aware of the config file and others not.
This is inconsistent...
I did not expect empty login values though...
So i must have failed in the login input by accepting empty values (yes i did... https://github.com/org-trello/org-trello/blob/master/org-trello-controller.el#L616, https://github.com/org-trello/org-trello/blob/master/org-trello-input.el#L17). I should have used https://github.com/org-trello/org-trello/blob/master/org-trello-input.el#L8.

Anyway, I assume you have only 1 identity (ocharles).
Because <kbd>M-x org-trello-install-board-metadata</kbd> ask you for the user to use except (when there is only one and use the one). As the user is empty, i'm not sure that the file is then correctly loaded...

Thus maybe the problem here.

Anyway, please, try to rename `~/.emacs.d/.trello/.el` to `~/.emacs.d/.trello/ocharles.el` and check again the install board and metadata routine.

Cheers,

**Comment by ocharles** [comment] 2016-02-11 13:06
Hi, that is indeed me - and thanks for the detailed report! I was also suspicious of that file, and renaming it has fixed things. Perfect!

**Comment by ocharles** [comment] 2016-02-11 13:12
Ok, never mind that comment about organisations - I forgot to actually "join" the board on Trello :)

**Comment by ardumont** [comment] 2016-02-11 13:14
> Hi, that is indeed me - and thanks for the detailed report! I was also suspicious of that file, and renaming it has fixed things. Perfect! 

Cool.

> However, I only see my own boards, not boards from organizations.

That's not supposed to be.
I do not reproduce. I'm part of one and i see those.

Do you see such board from your trello account?...

> Ok, never mind that comment about organisations - I forgot to actually "join" the board on Trello :)

lol, yeah, shit happens :D

Ok. Cool then!

I left this open and i'll close it when the bug is fixed.

Thanks for raising this up.

Cheers,

**Closed** 2016-02-13 19:07 UTC
Labels: bug, next-release
