### ISSUE TITLE
Stuck on a :PROPERTY: list

### ISSUE THREAD

**Issue by vandr0iy** [org-trello/org-trello#374] opened 2018-01-09 13:26 UTC
## bug?
Not sure

### M-x org-trello-bug-report
```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26)
 of 2017-12-04
- org version: 9.1.2
- org-trello version: 0.8.0
- org-trello path: /home/vandr0iy/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

### Expected behavior
I just ran `C-u M-x org-trello-sync-buffer` as shown in the `usage` section of the org-trello documentation section, and the list described in the `actual-behavior` section came out, while I was expecting something like the checkbox list shown in the documentation sites' `usage` section. It's working properly, apparently, since the labels/usernames are correct, and `M-x org-trello-check-setup` returns OK.
However, I started using org-mode very recently and there's no real clue anywhere on how to proceed from here, so I'm basically stuck. 

I tried with some various sparse tree commands `C-c / `, but apparently it searches only in the current document. The agenda commands, `C-c a`, return some results but I can't see any columns. Is there any documentation about this view?
### Actual behavior
This is what I see in my org buffer:
```
:PROPERTIES:
#+PROPERTY: board-name XXXX
#+PROPERTY: board-id 597b11e9d432c5d6c7f7d6b8
#+PROPERTY: Cancelled 597b12093ac9346f49159b9d
#+PROPERTY: On-Hold 59cdf232fe03757fd168a510
#+PROPERTY: Prod-Archive 597b11fecfbc0d87b88d1f7f
#+PROPERTY: Latest-Prod 5a2eb4a36418a92d6f5a14b4
#+PROPERTY: Test 597b11fb00d71196ddcfe7dc
#+PROPERTY: Merged 59a562ccc8b453125fea67c5
#+PROPERTY: In-Review-/-PR-created 599448a870ab797248b81d31
#+PROPERTY: In-Progress 597b11f75060b49a32c52ba5
#+PROPERTY: Ready 597b11ee8c2a5b2c758a3627
#+PROPERTY: Unready 597b11ec3464854e64742dc3
#+TODO: XXXX/DI Unready Ready In-Progress In-Review-/-PR-created Merged Test Latest-Prod Prod-Archive On-Hold Cancelled
...
#+PROPERTY: orgtrello-user-me vandr0iy
:END:
```
Thank you anticipately

**Comment by ardumont** [comment] 2018-03-07 07:53
> ... so I'm basically stuck.

Well, something seems off here.
The sync from board is apparently failing.
There should be some message in the **Message** buffer on what happened.

How big is your board?

> I tried with some various sparse tree commands C-c /, but apparently it searches only in the current document. The agenda commands, C-c a, return some results but I can't see any columns. Is there any documentation about this view?

I'm not sure what you are asking. What view?

The commands you mention are org-mode's, so heading to the org-mode documentation seems good.
The buffer you show is empty (aside from the properties mentioned), so you cannot do much.
The sync from (command you mentioned is that) must work first.

Cheers,

**Comment by cmatzenbach** [comment] 2018-09-22 21:33
I too have the same issue.  Here are the steps I took, from the beginning:

1. Installed the package, however using use-package instead of manual installation
2. Installed the key and token (using my email, which resulted in a problem later that I fixed by syncing again using my trello profile name)
3. Created an empty org file to house the board on my file system.  Set it in here:
`(custom-set-variables '(org-trello-files '("~/Projects/myproject/myproj.org")))`
4. Went to file, verified org-trello minor mode was loaded.  I did get the message "Non-existent agenda file ~/Projects/myproject/myproj.org. [R]emove from list or [A]bort?"  I chose R and A and neither seemed to affect my issue.
5. I run `M-x org-trello-install-board-metadata`, choosing my trello username this time, and selecting the board I want.  It reports it is successful, and I now see :PROPERTIES: in my buffer with an arrow to the right of it, my custom icon for expandable org lists
6. However, nothing I do expands it.  Tab doesn't work, Shift+Tab doesn't work, none of the `M-x org-show-*` commands work.  I do `M-x C-u C-c o s` and it says "No cards to sync".  What's weird is, if I cat the org file from a terminal, I see a file that starts with :PROPERTIES:, has a bunch of `#+PROPERTY: {Board Name} {BoardID}` lines, and then has a :END:.  Nothing I do will make it expand to see those additional lines in GUI emacs though (emacs 25 on macOS).
6b. I did try using emacs -nw, and tab still didn't expand the list, _but_ Shift+Tab worked once - it expanded the list (it never worked after that, never collapses and re-showed the list).  

Here's my output from `M-x org-trello-bug-report`:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29) of 2017-11-03
- org-version: 8.2.10
- org-trello version: 0.8.0
- org-trello path: /Users/me/.emacs.d/elpa/org-trello-20180331/org-trello.el
- request-backend: curl
- kill-whole-line: nil

Hopefully this helps.  Thanks, and let me know if you would like me to file as a separate issue or soemthing (thought I would condense since I assume it is the same issue).

**Comment by ardumont** [comment] 2018-09-23 07:02
Hello,

Thanks for this thorough report, it's nice.
I don't know what's wrong either. 
So i'll reply on to what is possibly off.

> Installed the package, however using use-package instead of manual installation

Can we see the snippet?

I too used `use-package` but not everything is clear to me about its use.
What you described both seems like not the mode is not loaded entirely (org-trello, even org-mode).
As what i understood of use-package was to lazily load modes, the problem might come from that.

Have you tried a simple `(require 'org-trello)`?
From your org-buffer you want to use:
<kbd>M-: (require 'org-trello) RET</kbd>

> Went to file, verified org-trello minor mode was loaded. I did get the message "Non-existent agenda file ~/Projects/myproject/myproj.org. [R]emove from list or [A]bort?" I chose R and A and neither seemed to affect my issue.

> Installed the key and token (using my email, which resulted in a problem later that I fixed by syncing again using my trello profile name)
>...
> I run M-x org-trello-install-board-metadata, choosing my trello username this time

Yes, you hinted at it twice.
You need to use your trello login IIRC (that's to store your credential locally in ~/.emacs.d/trello/<trello-login>.el). You can tamper with this afterwards to fix stuff.

org-trello does nothing about agenda so that might be an org thing.
I don't think that's the cause of the current problem (it's possibly related to `not everything is loaded` i hint at though).

Cheers,

**Comment by cmatzenbach** [comment] 2018-10-08 05:28
Ok, so I went through and decided to do an install on a complete separate machine, my other laptop that runs Arch linux.  I ended up with the exact same problem, except I approached it your way:
1. Used the following lines to configure it in my init.el:
`(require 'org-trello)
(custom-set-variables '(org-trello-files '("/home/me/Projects/myprojetfolder/bgp-trello.org")))`
1a. My original use-package snippet was:
`(use-package org-trello
  :defer t
  :config (custom-set-variables '(org-trello-files '("/home/me/Projects/myprojetfolder/bgp-trello.org"))))`
2. When I loaded the bgp-trello.org file, I confirmed org-trello mode was activated through C-h m.
3. I ran `org-trello-install-key-and-token`, actually entered my trello username this time, which worked perfectly, giving me my consumer key and access token.
4. I then run `org-trello-install-board-metadata`, and it loads up all the boards in my account (so the previous step _must've_ worked).  I select the board I want, and I'm still greeted with:
`:PROPERTIES:`
with an arrow at the end, hinting it can be expanded, but Tab and Shift-Tab do nothing.  It's just one line with that one word surrounded by colons, but if you go to the next line, the next line is like 33 or something.  So line 1 is labeled correctly as one, but there's obviously a ton of hidden data in there that I can;'t figure out how to expand.  Also interesting, if I select the whole line 1 and copy it, and paste it a few lines below in the buffer, I see the other 32 hidden items.  Here's what I got when I copied and pasted below:
`:PROPERTIES:
#+PROPERTY: board-name BoardGamePrices
#+PROPERTY: board-id 540c88357bd121a9bccd4e77
#+PROPERTY: Archive 540c88357bd121a9bccd4e7a
#+PROPERTY: Done 540c88357bd121a9bccd4e79
#+PROPERTY: To-Do:-Andrew 58ae55b6025ffa6c0756c4b5
#+PROPERTY: To-Do:-Chris 5b60f9b3d05a88a1513ec886
#+PROPERTY: To-do:-Joe 55c772ae333a08983f6d4747
#+PROPERTY: To-Do:-Thomas 5511c6b4d8b19728e20e81b0
#+PROPERTY: Rob---Design 583f0320432ead1d57fb2206
#+PROPERTY: To-do:-Ben 5570ed53ab3177269816d95a
#+PROPERTY: To-Do---Frontend 540c88357bd121a9bccd4e78
#+PROPERTY: To-Do---Backend 54b46e20c675900d50ee5478
#+PROPERTY: Marketing-Ideas 5747521c0ad61dd00a99d8f3
#+PROPERTY: Ideas 540c9982e9002e3a1a0fb827
#+TODO: Ideas Marketing-Ideas To-Do---Backend To-Do---Frontend To-do:-Ben Rob---Design To-Do:-Thomas To-do:-Joe To-Do:-Chris To-Do:-Andrew | Done Archive
#+PROPERTY: orgtrello_user_andrewmassengale 5720c38fd94b3317e2b0d417
#+PROPERTY: orgtrello_user_robertberinti 52484800a12caf092b001b38
#+PROPERTY: orgtrello_user_josephharding 5725144a2a048fe734d05df0
#+PROPERTY: orgtrello_user_danbuzaid 4ffd9d1e8bf6ce476b0e62a8
#+PROPERTY: orgtrello_user_benpanzarino 540c992784b42b3826bd0a5a
#+PROPERTY: orgtrello_user_thomasklaursen 4f54cd17ab35cbfb2fad292e
#+PROPERTY: orgtrello_user_matzy_ 5afa64c5fadec2f20c5efab6
#+PROPERTY: :red
#+PROPERTY: :orange Login Experience
#+PROPERTY: :purple Scraper
#+PROPERTY: :pink SEO
#+PROPERTY: :blue Site Upkeep and Maintenance
#+PROPERTY: :green Revenue Item
#+PROPERTY: :yellow User Experience
#+PROPERTY: orgtrello_user_me matzy_
:END:`

I'm really confused as to what's going on.  Is that all the details it shows?  It doesnt show the ticket description?  And why can't I expand the initial list I import?  The copying and pasting works, but you can't collapse, it's like they're not connected as children to the bullet/list heading above them.

**Comment by ardumont** [comment] 2018-10-11 07:45
Hello, 

thanks for keeping up the investigation.

> I'm really confused as to what's going on. 

I am as well...
(keep on reading though ;)

> Is that all the details it shows? 

Those :properties: details at the top of the file are used by org-trello to know how to link your buffer to your trello accounts.

> It doesnt show the ticket description? 

That's the weird part.
You should see cards as TODO/IN-PROGRESS/etc... point (yours are: Ideas Marketing-Ideas To-Do---Backend To-Do---Frontend To-do:-Ben Rob---Design To-Do:-Thomas To-do:-Joe To-Do:-Chris To-Do:-Andrew | Done Archive)
Mmmm, that's weird, try removing that supplementary end-of-line, between Rob---Design and To-Do:-Thomas... I'm not sure org permits to have a property that is not inlined.

> And why can't I expand the initial list I import? 

Something impedes the writing to occurs properly.
Thus, it breaks and nothing shows accurately or shows at all.

Have you checked the *Messages* buffer?
Can you please report what's there? That might help.

> The copying and pasting works, but you can't collapse, it's like they're not connected as children to the bullet/list heading above them.

Smells like it's not writing at the right location.
And then everything goes awfully wrong.

Cheers,

**Comment by cmatzenbach** [comment] 2018-10-11 14:38
@ardumont No problem, this package looks amazing, can't wait to get it working!  It looks like when I try and press Tab (or expand the list in any way), I get the message `outline-back-to-heading: Before first heading` in the Messages buffer.  I did as you said with the copy and pasted text below in the buffer ("removing that supplementary end-of-line, between Rob---Design and To-Do:-Thomas"), and tried playing around - I still can't expand any of the lines that represent cards, or even collapse the whole list by pressing Tab on the :PROPERTIES: header on top, however, Shift+Tab does work _once_ - it will close the whole list, but never re-expand it.  I have to copy and paste again to see everything under :PROPERTIES:.  Should I be able to expand the individual cards to see further details?  If I press tab on any of those lines I get that same message in the Messages buffer.
I'm going to try re-syncing and see what happens in Messages.

**Comment by cmatzenbach** [comment] 2018-10-11 15:18
@ardumont Ok I just setup a new board in trello, making it super basic (the three standard lanes, and four tickets to test).  I ran `org-trello-install-board-metadata` and ended up with the exact same thing, a :PROPERTIES: list that looks expandable but I can't do anything for.  When I copied and pasted it below, here's what I got:

:PROPERTIES:
#+PROPERTY: board-name Org Trello Test
#+PROPERTY: board-id 5bbf662f88292001b57783e9
#+PROPERTY: Done 5bbf662f88292001b57783ec
#+PROPERTY: Doing 5bbf662f88292001b57783eb
#+PROPERTY: To-Do 5bbf662f88292001b57783ea
#+TODO: To-Do Doing | Done
#+PROPERTY: orgtrello_user_matzy_ 5afa64c5fadec2f20c5efab6
#+PROPERTY: :red
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :orange
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: orgtrello_user_me matzy_
:END:

Here's the output from the bug report for this new computer:

    system-type: gnu/linux
    locale-coding-system: utf-8-unix
    emacs-version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30
    org-version:9.1.9
    org-trello version: 0.8.0
    org-trello path: /home/me/.emacs.d/elpa/org-trello-20180331/org-trello.el
    request-backend: curl
    kill-whole-line: nil

**Comment by ardumont** [comment] 2018-10-11 15:54
> outline-back-to-heading: Before first heading

Those kind of errors i had when developing org-trello.
It was usually a problem of triggering an org action outside of where it was supposed to...
This does not say much than what i already said earlier.

What's the <tab> binding associated to in an org buffer?

In your org buffer :
```
C-h k RET TAB
or 
M-x describe-key RET
```

Mine is bound to org-cycle (both bare org-mode or with org-trello).

```
TAB runs the command org-cycle (found in org-mode-map), which is an
interactive autoloaded compiled Lisp function in
‘../prelude/elpa/org-20181008/org.el’.

It is bound to <tab>, TAB, <menu-bar> <Tbl> <Next Field>, <menu-bar>
<Org> <Show/Hide> <Cycle Visibility>.

(org-cycle &optional ARG)
```

Cheers,

**Comment by cmatzenbach** [comment] 2018-10-11 16:17
@ardumont Ok I see, you're right, I had the wrong command mapped to tab.  Using `org-cycle` does reveal the whole list under :PROPERTIES: (as pasting had done)!  However, I'm still confused on why I don't see any cards.  I tried `org-trello-sync-buffer`, but it says there are no cards to sync.  My file still looks exactly as it did above (I even added a new card to see if it would pick it up, but it didn't).  When watching your videos and looking at your docs, I see the card data after the :PROPERTIES: list.  Is there something I'm missing here to pull the cards down?
I tried running `C-c o c` on random #+PROPERTY items in the list, but it gave me an error saying I needed to be on an org-trello entity for this action to occur.  What am I missing?
Thanks for all your help!

**Comment by ardumont** [comment] 2018-10-11 16:21
> I tried running C-c o c on random #+PROPERTY items in the list, but it gave me an error saying I needed to be on an org-trello entity for this action to occur. What am I missing?

Set the caret in the buffer's body (not in the property drawer, that's the name IIRC).

Note:
Since the beginning, i realize i forgot to mention the <kbd>org-trello-check-setup</kbd> to check... the setup ;)

**Comment by ardumont** [comment] 2018-10-11 16:35
> Ok, so I am able to create cards, and it instantly pushes them to trello. 

\m/

> My question is, isn't there a way to import all the cards currently on trello, or does it only go from org -> trello? I want to pull all the cards currently on my board and import them into org - is that not possible?

Yes, it is.
That'd be #387#issuecomment-415736205

> By the way I had run the check-setup command early on, and it says everything is fine. C-c o c instantly pushing the created cards to my board seems to confirms that.

Ok, Yes, your setup was already correct...
Well, the part checked anyway (that'd be the trello credentials and the local setup to access the trello board).

The org part i do not check (here for example, it is assumed that the default tab is the org one and not something else). 

That must be one of the main reasons that when filing an emacs bug report, they ask for starting emacs without any other modules, just the bare emacs...

> C-c o c instantly pushing the created cards to my board seems to confirms that.

Indeed.

Cheers,

**Comment by cmatzenbach** [comment] 2018-10-11 16:41
@ardumont you are the best!!!!!  I saw the C-u binding on the guide, but I forgot I was using evil (c-u is scroll for us), so of course it didn't register as part of the key-chord.  Disabled evil, ran `C-u C-c o s` and everything appeared!!!  This is incredible - thank you so much for your attentive help and all the work you did in creating this package.  
Finally, one last question - is there an m-x command for that `C-u C-c o s` binding?  `C-h k` won't accept `C-u` and thus I'm not sure how to look it up (and it'd be preferable to disabling evil every time I need to run it).  
Thanks again!

**Comment by cmatzenbach** [comment] 2018-10-11 16:50
Ah one more thing.  I ran into [this issue](https://github.com/org-trello/org-trello/issues/385) when trying to sync my original board; I'm sure there are too many cards there.  Is there a way to only sync the cards from one lane?  All my cards are in a single lane for me - so I really just need to sync that one.  I'm fine messing around in the source (not good at elisp though) if you have an idea how I can hack around it.

**Comment by ardumont** [comment] 2018-10-11 16:52
Thanks for the kind words ;)

> Finally, one last question - is there an m-x command for that C-u C-c o s binding? 

Yes and no, all M-x commands exist (cf. below for the help command to describe those).
The C-u equivalent existed at some point but now they no longer do.
you need to `C-u M-x <command>`...

> C-h k won't accept C-u and thus I'm not sure how to look it up (and it'd be preferable to disabling evil every time I need to run it).

You can always check <kbd>M-x org-trello-help-describe-bindings</kbd> (C-c o h IIRC).
I did my best to summarize what those do (including the C-u modifier).

Cheers,

**Comment by ardumont** [comment] 2018-10-11 16:56
>  Is there a way to only sync the cards from one lane?

What's a lane?

Maybe that's worth closing this issue if we are good and moving on to the other one you referenced.

**Comment by cmatzenbach** [comment] 2018-10-11 16:57
Sure thing, will do.

**Comment by ardumont** [comment] 2018-10-11 16:59
Thanks.

**Closed by ardumont** 2018-10-11 16:59 UTC
Labels: need-feedback
