### ISSUE TITLE
Json-readtable-error when connect the org-mode file with a trello board

### ISSUE THREAD

**Issue by zfc09** [org-trello/org-trello#339] opened 2016-12-29 08:38 UTC
I have a setup problem. The org-trello setup `M-x org-trello-install-key-and-token` has been done. But when I connect the buffer to the board `C-c o I or M-x org-trello-install-board-metadata`, it will output
```
Board to install (TAB to complete): [No match]
```

Output in the Message buffer when I try to connect to the board:
```
org-trello - Install boards and lists...
Loading c:/.emacs.d/.trello/fucen.el (source)...done
org-trello - Install board metadata in buffer...
Contacting host: xxx.xxx.com:8080 (proxy url)
REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
org-trello - client - Problem during request - error-thrown: (json-readtable-error)
Contacting host: xxx.xxx.com:8080 (proxy url)
REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
org-trello - client - Problem during request - error-thrown: (json-readtable-error)
```

Output in *ielm* when I try 
```
(let ((org-trello--user-logged-in "fucen"))
         (orgtrello-controller-load-keys)
         (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
```
is nil. And Message buffer says
```
Loading c:/.emacs.d/.trello/fucen.el (source)...done
Contacting host: xxx.xxx.com:8080 (proxy url)
REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
org-trello - client - Problem during request - error-thrown: (json-readtable-error)
```

Result of `M-x org-trello-bug-report`
```
System information:
- system-type: windows-nt
- locale-coding-system: cp1252
- emacs-version: GNU Emacs 24.3.1 (i386-mingw-nt6.1.7601)
 of 2013-03-18 on MARVIN
- org version: 7.9.3f
- org-trello version: 0.7.9
- org-trello path: c:/.emacs.d/elpa/org-trello-0.7.9/org-trello.el
- request-backend: url-retrieve
```

Customization:
```
For help using this buffer, see Easy Customization in the Emacs manual.

                                          Search 

Operate on all settings in this buffer:
 Revert...   Apply   Apply and Save 


Parent groups: Org

Org-trello group:  Org-trello customisation group.
       State : something in this group has been set and saved.
   
Hide Org Trello Current Prefix Keybinding: C-c o
    State : SAVED and set.
   The default prefix keybinding to execute org-trello commands.

Show Value Org Trello Files 
   Org-trello files that needs org-trello activated when opened. More

Show Value Org Trello Input Completion Mechanism 
   The completion mechanism the user can choose from. More

Show Value Org Trello Mode Hook 
   Define org-trello hook for user to extend mode with their own behavior.

Show Value Orgtrello Log Level 
   Set log level. More

Show Value Orgtrello Setup Use Position In Checksum Computation 
   Let the user decide if (s)he wants to use the position in the checksum. More

```

Thanks very much!

**Comment by ardumont** [comment] 2016-12-31 19:19
Hello,

From the top of my head, the only thing i can think of regarding this thorough report (thanks by the way)  is that the proxy does not return json as expected.

Then, the callback function fails ungracefully to parse the response.

So, the proxy might return an error in html.
Now, we'd need to check that that's actually what happens :D

Cheers,

**Comment by zfc09** [comment] 2017-01-17 01:24
How can i help on resolving this issue for next step ? The proxy is running well. I use it everyday.

**Comment by ardumont** [comment] 2017-01-18 08:58
Hello,

Sorry for the late reply.

> How can i help on resolving this issue for next step ? 

Be more verbose on org-trello's side would be a start...
Oh wait, now I remember an old issue which looks like yours (o.s. is windows-like, with proxy and trying to investigate the issue with more verbosity on the log).
Can you please take a look at #287 and see if that helps?

You can report back in the information you found here.

> The proxy is running well. I use it everyday.

I have no doubts.
Since I did not test org-trello through proxy though, that's the only thing that come to mind in regards to failure for now.

I sure hope that some clouds will be blown away by your results :D.
Which will permit us to see more clearly the root cause of the failure.

Cheers,

**Comment by zfc09** [comment] 2017-01-20 03:57
> Can you please take a look at #287 and see if that helps?

I think this is exactly the same issue i encountered.

I also tried other urls in ielm. I found HTTP url will be working, while HTTPS request will fail.

For example:
`(with-current-buffer (url-retrieve-synchronously "http://www.baidu.com")
  (prog1
      (buffer-string)
    (kill-buffer)))`
will success, 

while
`(with-current-buffer (url-retrieve-synchronously "https://trello.com/")
  (prog1
      (buffer-string)
    (kill-buffer)))`
will fail.

And the failure return is the same as [#287](https://github.com/org-trello/org-trello/issues/287).
`"HTTP/1.1 400 Bad Request\nCache-Control: no-cache\nPragma: no-cache\nContent-Type: text/html; charset=utf-8\nProxy-Connection: close\nConnection: close\nContent-Length: 727\n\n<HTML><HEAD>
\n<TITLE>Request Error</TITLE>
\n</HEAD>
\n<BODY>
\n<FONT face=\"Helvetica\">
\n<big><strong></strong></big><BR>
\n</FONT>
\n<blockquote>
\n<TABLE border=0 cellPadding=1 width=\"80%\">
\n<TR><TD>
\n<FONT face=\"Helvetica\">
\n<big>Request Error (invalid_request)</big>
\n<BR>
\n<BR>
\n</FONT>
\n</TD></TR>
\n<TR><TD>
\n<FONT face=\"Helvetica\">
\nYour request could not be processed. Request could not be handled
\n</FONT>
\n</TD></TR>
\n<TR><TD>
\n<FONT face=\"Helvetica\">
\nThis could be caused by a misconfiguration, or possibly a malformed request.
\n</FONT>
\n</TD></TR>
\n<TR><TD>
\n<FONT face=\"Helvetica\" SIZE=2>
\n<BR>
\nFor assistance, contact your network support team.
\n</FONT>
\n</TD></TR>
\n</TABLE>
\n</blockquote>
\n</FONT>
\n</BODY></HTML>
\n"`

**Comment by ardumont** [comment] 2020-05-10 08:31
I realized i should have asked then to remove the proxy from the equation to
ensure it's the root issue.

As it's been years now, i'm closing this. I don't really expect much from
either the user or me ;)

Emacs, org-mode, org-trello all have improved since then.

Feel free to re-open (with updated information) if the issue is still there.

Cheers,

**Closed** 2020-05-10 08:51 UTC
Labels: proxy
