### ISSUE TITLE
org heading structure breaks after 1st comment in org-mode 8.3beta

### ISSUE THREAD

**Issue by emelin** [org-trello/org-trello#232] opened 2015-01-04 17:46 UTC
!!!! Thank you so much for the extended comment support (#227) !!!!

It works like a charm!

The only unfortunate thing is, that I need to work with org-mode 8.3beta and there the heading structure breaks after the first comment. 

I guess this happens due to an text overlay problem since this issue only occurs, if org-trello-mode is switched on.

I hope this is not a big thing issue. Maybe you would want to take a look at this, before the soon upcoming release of org-mode 8.3.

Here is the reproducible symptom in detail:

0) Switch to org-mode version 8.3beta.
1) Create a new trello board (on trello) with one card and add a comment.
2) Create a second comment or another card.
2) C-c o I  and  C-u C-c o s  in order to sync the whole board.
3) The org-buffer looks perfect, but as soon as I save it (C-x C-s) everything below the first comment appears as text and the stars of all following headlines are not color-coded anymore. As a result, if I want to sync the buffer back to trello, the whole board will be messed up completely.
4) Crosscheck: When reverting the buffer (state before saving) and switching off org-trello-mode then saving the buffer works perfectly.

**Comment by ardumont** [comment] 2015-01-04 19:33
Hello,

Thanks for the feedback about the comments evolution.
Glad to hear it helps.

I'm not near my computer right now.

But indeed org-trello does some action when saving the buffer through hooks.

The org-mode dev might have changed something in their api... That now
break on org-trello.

Thanks for the heads up.

For my information, what's so great in Org-mode beta 8.3? (I did not have
time to look).

Thanks

Cheers,

**Comment by emelin** [comment] 2015-01-04 19:46
Org-mode 8.3 simply changed some things regarding the exporter framework that my hacks depend on. Not a big revolution, but that's how I got "addicted" to it.

**Comment by ardumont** [comment] 2015-01-05 17:11
Can you please provide a sample of your text buffer (you can anonymise the ids)?

Thanks

**Comment by ardumont** [comment] 2015-01-11 10:51
Hello,

Some news about this, first [install org-mode from source](https://github.com/ardumont/org/blob/master/org-mode/compile-org-mode.org).

Now I am in version `8.3.0-fake` (latest source code as of today the 11th of january 2015).

Then create comments:

```org-mode
:PROPERTIES:
#+property: board-name foobar
#+property: board-id foobar
#+PROPERTY: DONE bar
#+PROPERTY: TODO foo
#+TODO: TODO | DONE
#+PROPERTY: orgtrello-user-ardumont blah
#+PROPERTY: :orange
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: :red
#+PROPERTY: orgtrello-user-me ardumont
:END:

* TODO new card
  :PROPERTIES:...

  - [-] hello
    - [ ] there
** COMMENT ardumont, 2015-01-11T10:35:56.135Z
:PROPERTIES:...
anoter comment** COMMENT ardumont, 2015-01-11T10:35:45.176Z
hello there
...
```

First problem I see is that it's missing an end of line between the 2nd comment and the first one.
Which indeed mess up the buffer.

This somehow did not appear in previous org-mode version.

If you insert an end of line character, this seems to no longer do the trick. Do you confirm?

(I'll fix this in next release of course.)

Cheers,

**Comment by ardumont** [comment] 2015-01-13 16:03
Hello,

did you have time to test what I propose?

Cheers,

**Comment by emelin** [comment] 2015-01-21 18:06
Hello, hello again! 
Back from holidays, I can now catch up with things again. Sorry for the delay.
First of all, yes I can conform, it is exactly this 'missing new line' behavior between comments that I experience as well.
So, very good that you could reproduce it right away.
If you could get rid of this, by somehow inserting the missing line-break. Voilà, I guess we are done :-))

**Comment by ardumont** [comment] 2015-01-23 09:46
> Hello, hello again!
> Back from holidays, I can now catch up with things again. Sorry for the delay.

No problem.

> First of all, yes I can conform, it is exactly this 'missing new line' behavior between comments that I experience as well.
> So, very good that you could reproduce it right away.

Indeed.

> If you could get rid of this, by somehow inserting the missing line-break.
> Voilà, I guess we are done :-))

Cool.

As soon as I have some time, yes.
    
> Thank you for taking the effort and checking against 8.3.0-fake!

Thanks for raising the issue.

**Comment by emelin** [comment] 2015-01-25 09:00
Guess this closing was a bit too quick!

Against which org-mode commit did you test the fix?

I am currently on org-mode 61eedb8 (the latest of today) and org-trello-20150124.1217 in ELPA.

The problems with the headline structure is still the same as described above.

Cheers,
Emelin

**Comment by ardumont** [comment] 2015-01-25 09:12
> Guess this closing was a bit too quick!

That's the beauty of it all.
Feedback.
If it was too quick, you can reopen it as quick :D

> Against which org-mode commit did you test the fix?

12fc68f3cd26d162c4ad59a8da7000a0a23b5d5e (11th of january 2015).

> I am currently on org-mode 61eedb8 (the latest of today) and org-trello-20150124.1217 in ELPA.
> 
> The problems with the headline structure is still the same as described above.

The pb may be because of how I implemented the solution - https://github.com/org-trello/org-trello/blob/master/org-trello-setup.el#L244

What's `M-: (org-version)` or `M-x org-version` gives you?

I believe you could fortunately tip-toe around like this:

```emacs-lisp
(custom-set-variables
 '(orgtrello/line-between-comments "\n"))
```

> Cheers,

Cheers

**Comment by emelin** [comment] 2015-01-25 09:29
Thanks for the quick response!

`M-x org-version` yields: 
    
    Org-mode version 8.3beta (release_8.3beta-751-g61eedb @ ...)

Setting `orgtrello/line-between-comments` to `"\n"` does *not* do the trick.

It is something more profound concerning how the AST is composed.

Did you test your fix? Did it ever work for you?

**Comment by ardumont** [comment] 2015-01-25 09:51
> Setting orgtrello/line-between-comments to "\n" does not do the trick.

Weird.

> It is something more profound concerning how the AST is composed.

I do not know.

> Did you test your fix? Did it ever work for you?


Yes and yes. Otherwise, I would not have deliver.

I keep reproducing the problem without the fix and the solution with the fix I propose:

- Clean emacs install.

- install org-mode 8.3 beta (my current version though cf. previous commit).

- Create scratch buffer and activate org-trello and attach board to it and create card

- Add 2 comments, the 2nd is messed up as per this issue's initial description

- Modify the `orgtrello/line-between-comments` to \n

- Fix comment 2 by inserting a line (to fix the previous trouble)

- Add 3rd and 4th comment, everything is good.

- Now update org-mode to latest commit (as of today 25th of january 2015 `61eedb852fe1ca80f28d2bdd0c069a5fa702b6b9
Refs: [master], {origin/master}, {origin/HEAD}, release_8.3beta-751-g61eedb8`)

- Remove `\n` from `orgtrello/line-between-comments`

- Add comments -> same pb

- Set orgtrello/line-between-comments to \n

- Create comments -> no more pb

What's the content of your `orgtrello/line-between-comments`?
(How do you set it?)

Cheers,

**Comment by emelin** [comment] 2015-01-25 12:57
Ok, let's track that thing down!

1. We are on the same org-mode commit -- good.
2. My eamcs is: GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) -- should be ok
3. We use the same org-trello version -- namely: org-trello-20150124.1217 in ELPA. -- good


What I do: 

* Start with an empty buffer.
* Set `orgtrello/line-between-comments` to `\n` via org-babel.
```
#+begin_src emacs-lisp
(setq orgtrello/line-between-comments "\n")
#+end_src
```
*  Conferm the change of this variable: 
```
orgtrello/line-between-comments is a variable defined in `org-trello-setup.el'.
    Its value is "
    "
    Original value was ""

    Documentation:
    A customizable property to add a line between comments.

    You can customize this variable.

    [back]
```
* `M-x org-trello-mode`
*  Conferm once more that the change of the variable is still in effect: 
```
orgtrello/line-between-comments is a variable defined in `org-trello-setup.el'.
    Its value is "
    "
    Original value was ""

    Documentation:
    A customizable property to add a line between comments.

    You can customize this variable.

    [back]
```
* `C-c o b` create a fresh board
* make two cards and sync `C-c o s`, such that the buffer now looks like this:
```
:PROPERTIES:
...
:END:
* TODO 1st
  :PROPERTIES:
  :orgtrello-id: 54c4e186fad3e1df2420057d
  :orgtrello-local-checksum: 986df979cb71aeec097bd2e1fd893379a2293bc2322342cf7a5fc6573cd0e9c8
  :END:
  1

* 2nd
  :PROPERTIES:
  :orgtrello-id: 54c4e1863d08b1b1688546dc
  :orgtrello-local-checksum: d8a7ebbd6bbfcc35c6e185ec846d881e81d3ca45b5b9bef685f9f0e095df216d
  :END:
  2
```
* beautiful!
* Now go to the first card and add a comment `C-c o C`.
* Finish entry of the comment by `C-c C-c`.

Without doing anything else, the result shows the trouble already: the 1st card and first comment are correct, but the headline of the 2nd is broken! It become part of the first comment:
```
:PROPERTIES:
...
:END:
* TODO 1st
  :PROPERTIES:
  :orgtrello-id: 54c4e186fad3e1df2420057d
  :orgtrello-local-checksum: 986df979cb71aeec097bd2e1fd893379a2293bc2322342cf7a5fc6573cd0e9c8
  :END:
  1
** COMMENT mc4mc, 2015-01-25T12:30:17.920Z
:PROPERTIES:
:orgtrello-id: 54c4e1d9a262d78d3aa5592f
:orgtrello-local-checksum: 29ab9231e070f6f784e8729a13b2dc6358e83f7d05994d7f54dd7cc778083a35
:END:
  first comment


  * 2nd
    :PROPERTIES:
    :orgtrello-id: 54c4e1863d08b1b1688546dc
    :orgtrello-local-checksum: d8a7ebbd6bbfcc35c6e185ec846d881e81d3ca45b5b9bef685f9f0e095df216d
    :END:
    2
```
* If we continue to add another comment to the 1st card. The result is desastrous and looks like this:
```
:PROPERTIES:
...
:END:
* TODO 1st
  :PROPERTIES:
  :orgtrello-local-checksum: 83e85db9c9d63c0d02d3b6963b56047e7e04c1d5c99fe2a73ed54bc903bbb545
  :orgtrello-id: 54c4e186fad3e1df2420057d
  :END:
  hello
  - [-] COMMENT mc4mc, 2015-01-25T12:30:17.920Z :PROPERTIES: {"orgtrello-id":"54c4e1d9a262d78d3aa5592f","orgtrello-local-checksum":"2ac31d17ae7c394e69ddf09073e9bc90d7ca08c84bdf2b56c75023d2073e064e"}
** COMMENT mc4mc, 2015-01-25T12:42:32.026Z
:PROPERTIES:
:orgtrello-id: 54c4e4b8a10aecddfc549b97
:orgtrello-local-checksum: 4f66ec46e9eae6f5936263f8b0373a9a40277c12dea6c19e16a4b3f4f15add84
:END:
  second comment
  ** COMMENT mc4mc, 2015-01-25T12:30:17.920Z
  :PROPERTIES:
  :orgtrello-id: 54c4e1d9a262d78d3aa5592f
  :orgtrello-local-checksum: 447296fda8680d75a94b97799cbe2b310d68441d2107ea0192d37cda24aa6463
  :END:
  first comment
```
Yes, this is whole buffer, the 2nd card has even been deleted!

Please confirm, if this easily reprodued steps lead to the same, similar or other results.

In general, I guess, the trouble results from not altering or deleting org-elements in the expected way, such that the AST of the org-buffer gets corrupted. I fear that adding some `\n` chars between the lines is mere cosmetics and not the right approach to solve the issue.

Thanks for your efforts,
Emelin

**Comment by ardumont** [comment] 2015-01-25 13:38
Ok.

Now I see when I did not before.
And indeed, I reproduce something similar.
For cards without checklist or description, something awry happens along what you describe pretty well.

So, the pb seems at least double, first, there is the missing line which collides 2 comments in one line.

Second, there is also an indentation of the 2nd level header (comments) which is not supposed to happen. 

(Also, as a consequence, I believe if you look at your card in the trello board (after sync of your card), you should see the comments in the card's description...).

Definitely some thing(s) to fix here.

--

I reopen this but you could have.
For me, if we discuss something, confirmed or not, you can open.
(I close because it's part of my workflow during dev using github instruction in commit but it's not set in stone, far from it).

Cheers,

**Comment by ardumont** [comment] 2015-01-25 13:48
Also, I believe I found the culprit

```lisp
(orgtrello-entity/card-metadata-end-point!)
```

With no description or checklist, this does not stop to comments.
Thus integrating comments in the description when parsing the file.
Thus integrating org keywords in the description.
Thus when writing back in org buffer (after a sync from for example), losing any consistency...
Thus experiencing the nightmarish hell you describe...

**Comment by emelin** [comment] 2015-01-25 13:53
All right. Good to hear that it was reproducible at your side and that we are back in sync! 

That's the most important, first of all.

Oh (your 2nd posting came just in) and even a promising candidate ... all the better!

From my experiece, the master branch of org-mode is kept extraordinary stable and lots of people are using it. So, getting in complience with it, I think, is worth the effort.

**Comment by ardumont** [comment] 2015-01-25 14:28
Hello again,

I've pushed a fix. 
This seems fixed by my manipulation.
Can you please shake this on your side too?

To load org-trello from the code, add my repository as remote, checkout the branch 0.6.9.1 and then you can load the "load-org-trello.el" file by `M-x eval-buffer`.
(`M-x org-trello/version` to check the version is loaded.)

Thanks

Cheers,

**Comment by emelin** [comment] 2015-01-25 19:10
Oh cool! 

Yes, I would like to test this. But I can't find that branch. There seem to be only two in the repo.

Or what shall it mean to "add a repository `as remote`"?

**Comment by ardumont** [comment] 2015-01-25 20:03
> Or what shall it mean to "add a repository as remote"?

The official org-trello's git repository is no longer ardumont/org-trello but org-trello/org-trello.
Still, I create branch on my fork and propose Pull Request from my fork.

Thus, to add my repo ardumont/org-trello as remote:
```sh
git add ardumont-fork git@github.com:ardumont/org-trello.git
git fetch ardumont-fork
git checkout ardumont-fork/0.6.9.1
```

Cheers,

**Comment by emelin** [comment] 2015-01-26 11:47
Hurray! Now the above test works!

Thanks for pointing me to right repository.

Yet there is still a little oddity: If I add some text to a card and press enter, the text gets indented. This is very odd and does not happen, if you switch off `org-trello-mode` and then perform the same action in in the same buffer. This indenting leads to a forced highlighted card description on the trello-board which is not always desired. (See the numbers 1 and 2 in the sample below; they are indented)

Another oddity is that `C-c o s` (which is supposed to sync the whole buffer) does not delete comments, if you have deleted them in the buffer. You need to go comment by comment and delete each one seperately by `C-u C-c o U`. That's pretty inconvenient, in the long run.

Best,
Emelin

```
* TODO 1st card
:PROPERTIES:
:orgtrello-local-checksum: 4250fe66fa983aee8e4d57281b54a2cee87a38abfaefa0696fc596e2f6d5e51b
:orgtrello-id: 54c6233c2a684f57ddeab5df
:END:
  1

** COMMENT mc4mc, 2015-01-26T11:22:25.053Z
:PROPERTIES:
:orgtrello-id: 54c62371f029a5c5ddc1fb70
:orgtrello-local-checksum: af7b6c454c48136960c8e48efb6e72f9e04f5397c2c4ea345c3bca027d8de3d0
:END:
second comment
edit second comment

** COMMENT mc4mc, 2015-01-26T11:21:47.751Z
:PROPERTIES:
:orgtrello-id: 54c6234b2b019d382ff358f8
:orgtrello-local-checksum: be9b9fba4202cfb88b41de123fc2e2d43ea3198d29bdffd280369cfd3bb3c6a6
:END:
first comment

* 2nd card
:PROPERTIES:
:orgtrello-id: 54c6233cfc9e5e1547def94a
:orgtrello-local-checksum: 574c020c73fc3e55423ef2d79149bf76ab2609569ad90f07d8c17049340a0945
:END:
  2
```

**Comment by ardumont** [comment] 2015-01-26 16:03
> Hurray! Now the above test works!

Great.

> Thanks for pointing me to right repository.

You're welcome.

> Yet there is still a little oddity: If I add some text to a card and press enter, the text gets indented. This is very odd and does not happen, if you switch off org-trello-mode and then perform the same action in in the same buffer. This indenting leads to a forced highlighted card description on the trello-board which is not always desired. (See the numbers 1 and 2 in the sample below; they are indented)

It's org-trello's intended behavior for those who want to add markdown in their card description.
https://github.com/org-trello/org-trello/search?q=markdown&type=Issues&utf8=%E2%9C%93

Markdown can use `-` but `-` has also another sense in org-mode (and also in org-trello...).
So using indentation was the only way found at the time to be able to differentiate.

> Another oddity is that C-c o s (which is supposed to sync the whole buffer) does not delete comments, if you have deleted them in the buffer. You need to go comment by comment and delete each one seperately by C-u C-c o U. 

Yes, this is the current behavior.
Please open new issues to propose enhancements.
(We can also discuss those specific enhancements there.)

> That's pretty inconvenient, in the long run.

Yes, possibly if you go and remove often comments (please again open an enhancement issue so we can discuss in a dedicated thread).

Also, I'm open to Pull Requests, that could make things happen faster :D 

Cheers,

**Comment by rwalkerands** [comment] 2015-02-02 07:11
I've just installed org-trello (from melpa, org-trello-20150127.1013, shows as version 0.6.9.1), and I'm seeing this problem.

I'm using Mac Emacs 24.4.1, which comes with org-mode 8.2.10. (I confirmed M-x org-version says 8.2.10.)

The value of orgtrello/line-between-comments is "". I tried setting it to "\n", but this made no difference.

Do I _have_ to use org-mode 8.3?

**Comment by ardumont** [comment] 2015-02-02 08:45
Hello,

> I've just installed org-trello (from melpa, org-trello-20150127.1013, shows as version 0.6.9.1), and I'm seeing this problem.
> I'm using Mac Emacs 24.4.1, which comes with org-mode 8.2.10. (I confirmed M-x org-version says 8.2.10.)
> The value of orgtrello/line-between-comments is "".

> I tried setting it to "\n", but this made no difference.

This is weird.
The default value is conditional on the org-mode version (8.3 being the conditional value) but the user can override this to have anything on it anyway (provided he/she customizes it).

Ok, so I have 2 problems to solve :D 
why do you have such behavior on org-mode 8.2.10?
and why the customizable value does not work...

> Do I have to use org-mode 8.3?

No, you should not have to.
It was a fix for the org-mode's coming version 8.3.
This behavior was not detected before.
I'll investigate when I have some time.

In the mean time, can you insert an end of line in your comment buffer?
Does it change anything?

Cheers,

**Comment by ardumont** [comment] 2015-02-02 16:55
> Ok, so I have 2 problems to solve :D

(talking to myself) you mean `understand` first, right!?

>    why do you have such behavior on org-mode 8.2.10?

I can reproduce this behavior on 8.2.10 too.
I should have been more cautious when trying to reproduce this initial issue.
I have been too focused on installing the latest org-mode...
My bad!

It's not an org-mode version problem, it's an org-trello pb completely independent from org-mode.

>    and why the customizable value does not work...?

Using this custom variable however fix the issue.

I think I will remove this now useless custom variable and insert an end of line between the user's comments.

--

Can you tell me first if you still have the issue with this code?

```lisp
(defun orgtrello-buffer/--serialize-comment (comment)
  "Serialize COMMENT as string."
  (let ((comment-user (orgtrello-data/entity-comment-user comment))
        (comment-date (orgtrello-data/entity-comment-date comment))
        (comment-string (orgtrello-data/entity-comment-text comment))
        (comment-id (orgtrello-data/entity-comment-id comment)))
    (format "\n** COMMENT %s, %s\n:PROPERTIES:\n:orgtrello-id: %s\n:END:\n%s\n" comment-user comment-date comment-id comment-string)))
```

*Note* 
Copy/paste (kill/yank) this in your *scratch* buffer, then <kbd>M-x eval-buffer</kbd>.
If you do this, you monkey-patch your org-trello install (boo!).

Then add new comments as usual.
Do you still encounter the erratic behavior or does this solve your issue?

@rwalkerands Thanks for getting back to me.

@emelin Can you try and check this too please?

Cheers,

**Comment by kmartino** [comment] 2015-02-02 19:06
I've tried the monkey patch above, and still have the issue.

**Comment by rwalkerands** [comment] 2015-02-02 22:46
No difference. :-( I have tried debugging. The problem seems to occur soon after inserting the checksum; point is then "restored" (by save-excursion?) at the end of the _text_ of the comment, not at the end of what was inserted (i.e., the newline).

**Comment by kmartino** [comment] 2015-02-03 02:12
I see the same as @rwalkerands .

**Comment by ardumont** [comment] 2015-02-03 09:46
Hello,

Thanks guys for the feedback, it's cool to cross-check.

I see a difference though.
Now the comments seem ok by themselves. 
But where it fails is between the last comment and the next card.

I'm at work right now. I'll see what I can do this evening.

Cheers,

**Comment by kmartino** [comment] 2015-02-03 14:04
When there is a description on the card, that is correct. If you delete the description, and just have comments, the comments themselves indent as if they are part of the description.

**Comment by ardumont** [comment] 2015-02-03 14:08
> When there is a description on the card, that is correct. If you delete the description, and just have comments, the comments themselves indent as if they are part of the description.

Thanks. This helps.
This means that I must check the card's different region computation... (card metadata, card data, card comments region).

Cheers,

**Comment by ardumont** [comment] 2015-02-03 14:10
https://github.com/org-trello/org-trello/blob/master/org-trello-entity.el#L160-L175

**Comment by kmartino** [comment] 2015-02-04 01:51
I think I understand. What can we do to help you debug? Do you have another code snippet?

**Comment by ardumont** [comment] 2015-02-04 07:10
> I think I understand. What can we do to help you debug? 

I like this thank!

But I do not know.
To where are you willing to follow?

> Do you have another code snippet?

Nope.
Unfortunately, yesterday evening, I tried to narrow this one but got no fixup code.
What I could gather was that indeed, the comments are indented as the description when there is no description nor body card (no checklist and no item)...

This should not happen.

My next step now that I can reproduce this live would be to capture this in an integration test...

Cheers,

**Comment by kmartino** [comment] 2015-02-04 12:03
How do you run/write integration tests ?  Maybe I can help write it.

**Comment by ardumont** [comment] 2015-02-04 12:09
Like this non finished commit (started on the train this morning...)
https://github.com/ardumont/org-trello/commit/e2fe1e4e1002e604e34a82186d63ee4c2c354644

**Comment by ardumont** [comment] 2015-02-04 12:16
I use some internal tests macros in `test/utilities-test.el` which permits to manipulate org-trello-mode buffer. This way, I can try and test a function in a buffer in a repeatable way.

For the moment, I do not succeed in capturing this behavior in the test but I do in runtime...
It's work in progress (not right now though, I'm at work) but if you want to give it a try, it's cool.

Thanks.

--

You need [Cask](https://github.com/cask/cask) to dev/test locally.
To trigger the test in a dedicated instance, it's:
```sh
make test
```

**Comment by ardumont** [comment] 2015-02-04 18:24
I did not successfully find out how to test this yet.

But with this, I do no longer see the erratic behavior.

```lisp
(defun orgtrello-buffer/--write-card-description! (description)
  "Write at point the current card's DESCRIPTION if present (and indent it)."
  (when (and description (not (string= description "")))
    (let ((start (point)))
      (insert (format "%s" description))
      (indent-rigidly start (point) *ORGTRELLO-BUFFER/INDENT-DESCRIPTION*))))
```

**Comment by ardumont** [comment] 2015-02-04 18:26
Scratch that!
joy of dynamic!

**Closed** 2015-02-09 11:56 UTC
Labels: bug, investigate, next-release
