### ISSUE TITLE
Bug: Initial sync results in "FAILED. Error: (wrong-type-argument" error

### ISSUE THREAD

**Issue by wakatara** [org-trello/org-trello#386] opened 2018-06-10 11:40 UTC
## Bug

Yup. 
(I am using terminal emacs if you think that makes a difference)

### M-x org-trello-bug-report

```
System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0)
 of 2018-05-29
- org version: 9.1.13
- org-trello version: 0.8.0
- org-trello path: /Users/daryl/.emacs.d/elpa/org-trello-20180330.2331/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

### Expected behavior

C-u C-c o s for the initial sync was expected to sync my initial Trello board down to the specified org-mode file.

### Actual behavior

Did not happen. Instead I received the error:

```
FAILED. Error: (wrong-type-argument sequencep #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
```

### Steps to reproduce the behavior

1. Go through standad install and setup (auto via the melpa repo)
2. Get consumer and secret key installed (yup)
3. Paste properties into the appropriate file
4. Trigger C-c o s

**Comment by kqr** [comment] 2019-07-08 10:06
I also get this in non-terminal Emacs – but not for all boards! I have tested on two boards, and only one of them produces this error (but does so reliably.)

**Comment by kqr** [comment] 2019-07-08 10:11
I have done some digging and what I know is this: `orgtrello-controller--sync-buffer-with-archived-and-trello-cards` gets called with one argument `data`, which is a list where the `car` is a `hash-table` and gets assigned to the variable `trello-cards`. Then the function attempts to run `(mapcar #'orgtrello-data-to-org-trello-card trello-cards)`. This blows up because `trello-cards` is a `hash-table`, and not a sequence.

Since Elisp is untyped, I can't see where the expected type goes wrong – we can only hope a maintainer more familiar with the code happens to know that.

**Comment by kqr** [comment] 2019-07-08 10:13
When debugging the same function on the board that works, it appears that `trello-cards` is supposed to be a list of hash-tables, where each hash-table corresponds to a card. I'll see what it actually is on the broken board.

**Comment by kqr** [comment] 2019-07-08 10:20
Yes, looking very closely at the logs (hard when they contain the full Trello card bodies as well!) reveals a sinister "org-trello - client - Problem during request - error-thrown: (error http 403)". In other words, this is a duplicate of #385 and can be closed as such.

**Closed** 2019-07-10 12:45 UTC
Labels: duplicate
