### ISSUE TITLE
Issue with non-latin characters

### ISSUE THREAD

**Issue by d1823** [org-trello/org-trello#340] opened 2017-01-06 16:29 UTC
Hey. First, I wanted to send you some big THANK YOU for such a great Emacs mode. Amazing job!

Now, when it comes to some corner case I hit recently. I'm from Poland, and I found that org-trello doesn't work so well with cards consisting of Polish characters when trying to sync with Trello. Now, I'm not really sure whether it's an issue with org-trello, my Emacs build, or my OS X configuration. Thus, this bug report. Any ideas?

### M-x org-trello-bug-report

```
System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, NS appkit-1504.76 Version 10.12.2 (Build 16C67))
 of 2017-01-04
- org version: 8.2.10
- org-trello version: 0.7.9
- org-trello path: /Users/dwolosowicz/.emacs.d/elpa/org-trello-20160604.645/org-trello.el
- request-backend: curl
```

### Expected behavior

Cards with characters outside of Latin subset should be synchronized with Trello correctly.

### Actual behavior

`(org-trello-sync-card)` used via `C-c o c` as well as `(org-trello-sync-buffer)` used via `C-c o s` does not work correctly when syncing cards with non Latin characters to Trello. You can create such cards on Trello, and org-trello will fetch and display them correctly, but any change on an existing ones, or a try to create a new one will result in failure. 

When you try to create a new card with the label consisting on non Latin characters (ex `ąęść`), org-trello will prompt you to choose the orgtrello-id value. It doesn't matter what you choose, the following result happens:

```
org-trello - Request ’sync entity with structure to trello...
Loading /Users/dwolosowicz/.emacs.d/.trello/dawidwolosowicz.el (source)...done
org-trello - Synchronizing card on board ’Doc Flow’...
REQUEST [error] Error (error) while connecting to https://api.trello.com/1/cards/.
org-trello - Newly entity ’ąęść’ with id ’nil’ synced!
```

### Steps to reproduce the behavior

In my case it's a matter of trying to sync this:

```
* ąęść
```

to get this:

```
* ąęść
  :PROPERTIES:
  :orgtrello-id: orgtrello-marker-c7b2397a69e0310043f86d6c45976d28b3f3c3ef
  :END:
```

If you try to sync something with Latin characters only:

```
* aesc
```

you'll get

```
* aesc
  :PROPERTIES:
  :orgtrello-id: 586fc5b530fb4901d7e75539
  :orgtrello-local-checksum: 6eeda5f6ca824221b57c100d0c708e401c016411ae9868f393f71bc5610d9623
  :END:
```

**Comment by ardumont** [comment] 2017-01-10 10:02
Hello,

Sorry for the late reply.
Thanks for the thorough report.

> Hey. First, I wanted to send you some big THANK YOU for such a great Emacs mode. Amazing job!

Hey, thanks!

> ...

I do agree with all that was said.
I reproduce this issue.
I'm befuddled, this is related to #307 #318 and i thought this was fixed.

Not that it matters much (it's a bug anyway) but I'm wondering if i can reproduce this in emacs24.

Cheers,

**Comment by Tritlo** [comment] 2017-04-04 18:40
I am also having this bug. Syncing non-latin from trello works fine, but when I sync them from `org-trello`, they get turned to question mark boxes on trello, and then when I sync back, they become question mark boxes in the org buffer.

**Comment by gariepyalex** [comment] 2017-05-22 18:42
Debugged it a bit and I thing the problem is emacs-request, not org-trello.
By setting ```(custom-set-variables '(request-message-level debug))```, you can see in the log that the payload is not encoded correctly.

It seems that this commit is at fault: https://github.com/tkf/emacs-request/commit/fb93d112750b3cddb65dbbf884edbce38cf578fd

I replaced it by
```elisp
(let ((file-coding-system-alist nil)
             (coding-system-for-write 'utf-8))
         (with-temp-file tempfile
           (setq buffer-file-coding-system 'utf-8)
           (insert data)))
```
and now it works. 

I'll open an issue in emacs-request's repo.

**Comment by ardumont** [comment] 2017-05-24 11:05
@gariepyalex Thanks, very much appreciated!

Cheers,

**Comment by HIRANO-Satoshi** [comment] 2017-06-28 06:57
Hi,

This issue is very serious for non-English users. 

@gariepyalex I confirmed your fix worked for Japanese at my site.

**Comment by gariepyalex** [comment] 2017-06-28 18:08
https://github.com/tkf/emacs-request/pull/79

**Comment by oneyb** [comment] 2017-08-12 23:19
Hello all,
@gariepyalex, according to @abingham,  @tkf disappeared (https://github.com/org-trello/org-trello/issues/307#issuecomment-178425982). Thus @abingham took over and it may be necessary to redirect your pull request.

**Comment by ardumont** [comment] 2017-09-06 12:16
> Thus @abingham took over and it may be necessary to redirect your pull request.

Well, i thought so as well but [the melpa recipe still targets the tkf repository](https://github.com/melpa/melpa/blob/master/recipes/request)...

**Comment by ardumont** [comment] 2017-09-07 08:23
#367 got resolved with this patch as well...

**Comment by ardumont** [comment] 2020-05-21 09:11
My understanding is that this is dealt with.
Closing.

**Closed** 2020-05-21 09:12 UTC
Labels: bug, resolved
