### ISSUE TITLE
Chinese coding problem

### ISSUE THREAD

**Issue by ow-clare** [org-trello/org-trello#377] opened 2018-02-23 12:57 UTC
From Trello to org-trello， it's ok

But from org-trello to Trello，not ok 

![2018-02-23 8 37 10](https://user-images.githubusercontent.com/27838544/36595041-a4439446-18db-11e8-9861-d5a534d55c00.png)

![2018-02-23 8 36 34](https://user-images.githubusercontent.com/27838544/36595049-ae5a3c1e-18db-11e8-9bc6-0982a4a1f92c.png)

### M-x org-trello-bug-report
```
System information:
- system-type: darwin
- locale-coding-system: utf-8
- emacs-version: GNU Emacs 25.3.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76)
 of 2018-02-08
- org version: 9.1.6
- org-trello version: 0.8.0
- org-trello path: /Users/ANKERCS/.emacs.d/elpa/25.3/develop/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

```
======================================================================
1 -> (decode-coding-string "{\"id\":\"5a8fa34daa59220d6\",\"badges\":{\"votes\":0,\"attachmentsByType\":{\"trello\":{\"board\":0,\"card\":0}},\"viewingMemberVoted\":false,\"subscribed\":false,\"fogbugz\":\"\",\"checkItems\":0,\"checkItemsChecked\":0,\"comments\":0,\"attachments\":0,\"description\":false,\"due\":null,\"dueComplete\":false},\"checkItemStates\":[],\"closed\":false,\"dueComplete\":false,\"dateLastActivity\":\"2018-02-23T05:24:15.550Z\",\"desc\":\"\",\"descData\":{\"emoji\":{}},\"due\":null,\"email\":null,\"idBoard\":\"5a8f7fb2fb4eeaa68\",\"idChecklists\":[],\"idList\":\"5a8f80803de6612cef531f37\",\"idMembers\":[],\"idMembersVoted\":[],\"idShort\":3,\"idAttachmentCover\":null,\"labels\":[],\"idLabels\":[],\"manualCoverAttachment\":false,\"name\":\"-\357\277\275 zone\",\"pos\":447.5,\"shortLink\":\"LALOkQEy\",\"shortUrl\":\"https://trello.com/c/LALOkQEy\",\"subscribed\":false,\"url\":\"https://trello.com/c/LALOkQEy/3-%EF%BF%BD-zone\"}" utf-8)
1 <- decode-coding-string: "{\"id\":\"5a8fa34daa59220bb5e\",\"badges\":{\"votes\":0,\"attachmentsByType\":{\"trello\":{\"board\":0,\"card\":0}},\"viewingMemberVoted\":false,\"subscribed\":false,\"fogbugz\":\"\",\"checkItems\":0,\"checkItemsChecked\":0,\"comments\":0,\"attachments\":0,\"description\":false,\"due\":null,\"dueComplete\":false},\"checkItemStates\":[],\"closed\":false,\"dueComplete\":false,\"dateLastActivity\":\"2018-02-23T05:24:15.550Z\",\"desc\":\"\",\"descData\":{\"emoji\":{}},\"due\":null,\"email\":null,\"idBoard\":\"5a8f7fb2fb4e3f9f8\",\"idChecklists\":[],\"idList\":\"5a8f80803de6612cef531f37\",\"idMembers\":[],\"idMembersVoted\":[],\"idShort\":3,\"idAttachmentCover\":null,\"labels\":[],\"idLabels\":[],\"manualCoverAttachment\":false,\"name\":\"-� zone\",\"pos\":447.5,\"shortLink\":\"LALOkQEy\",\"shortUrl\":\"https://trello.com/c/LALOkQEy\",\"subscribed\":false,\"url\":\"https://trello.com/c/LALOkQEy/3-%EF%BF%BD-zone\"}"
```

`describe-coding-system` output:

```
Coding system for saving this buffer:
  U -- utf-8-unix (alias: mule-utf-8-unix)

Default coding system (for new files):
  U -- utf-8 (alias: mule-utf-8)

Coding system for keyboard input:
  U -- utf-8-unix (alias: mule-utf-8-unix)

Coding system for terminal output:
  U -- utf-8 (alias: mule-utf-8)

Coding system for inter-client cut and paste:
  U -- utf-8 (alias: mule-utf-8)

Defaults for subprocess I/O:
  decoding: U -- utf-8-unix (alias: mule-utf-8-unix)

  encoding: U -- utf-8-unix (alias: mule-utf-8-unix)


Priority order for recognizing coding systems when reading files:
  1. utf-8 (alias: mule-utf-8)
  2. iso-2022-7bit 
  3. iso-latin-1 (alias: iso-8859-1 latin-1)
  4. iso-2022-7bit-lock (alias: iso-2022-int-1)
  5. iso-2022-8bit-ss2 
  6. emacs-mule 
  7. raw-text 
  8. iso-2022-jp (alias: junet)
  9. in-is13194-devanagari (alias: devanagari)
  10. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312)
  11. utf-8-auto 
  12. utf-8-with-signature 
  13. utf-16 
  14. utf-16be-with-signature (alias: utf-16-be)
  15. utf-16le-with-signature (alias: utf-16-le)
  16. utf-16be 
  17. utf-16le 
  18. japanese-shift-jis (alias: shift_jis sjis)
  19. chinese-big5 (alias: big5 cn-big5 cp950)
  20. undecided 

  Other coding systems cannot be distinguished automatically
  from these, and therefore cannot be recognized automatically
  with the present coding system priorities.

Particular coding systems specified for certain file names:

  OPERATION	TARGET PATTERN		CODING SYSTEM(s)
  ---------	--------------		----------------
  File I/O      "\\.dz\\'"              (no-conversion . no-conversion)
                "\\.txz\\'"             (no-conversion . no-conversion)
                "\\.xz\\'"              (no-conversion . no-conversion)
                "\\.lzma\\'"            (no-conversion . no-conversion)
                "\\.lz\\'"              (no-conversion . no-conversion)
                "\\.g?z\\'"             (no-conversion . no-conversion)
                "\\.\\(?:tgz\\|svgz\\|sifz\\)\\'"
                                        (no-conversion . no-conversion)
                "\\.tbz2?\\'"           (no-conversion . no-conversion)
                "\\.bz2\\'"             (no-conversion . no-conversion)
                "\\.Z\\'"               (no-conversion . no-conversion)
                "\\.elc\\'"             utf-8-emacs
                "\\.el\\'"              prefer-utf-8
                "\\.utf\\(-8\\)?\\'"    utf-8
                "\\.xml\\'"             xml-find-file-coding-system
                "\\(\\`\\|/\\)loaddefs.el\\'"
                                        (raw-text . raw-text-unix)
                "\\.tar\\'"             (no-conversion . no-conversion)
                "\\.po[tx]?\\'\\|\\.po\\."
                                        po-find-file-coding-system
                "\\.\\(tex\\|ltx\\|dtx\\|drv\\)\\'"
                                        latexenc-find-file-coding-system
                ""                      (undecided)
  Process I/O	nothing specified
  Network I/O	nothing specified

```

There is a simple test
```
(decode-coding-string "name\":\"\357\277\275 zone\"" 'utf-8-unix)
```
it's return 

```
"name\":\"� zone\""

```
should display 

```
"name\":\"中文 zone\""
```

**Comment by ardumont** [comment] 2018-03-07 08:18
Hello,

Thanks for the thorough report.

I reproduce the simple test issue (i use utf-8 on my system as well)...

Unicode is hard.
At least for me...

But `decode-coding-string` is an emacs function, not sure what i can do here.

What does your org-trello buffer looks like?

Cheers,

**Comment by ardumont** [comment] 2018-03-09 07:53
@PierreTechoueyres kindly reminded me of his fix #373 integrated in my 0.8.1 branch (not yet merged).

```
(defun orgtrello-query--post-or-put (server query-map &optional success-callback error-callback authentication-p)
  "Execute the POST/PUT request to SERVER with QUERY-MAP with optional SUCCESS-CALLBACK, ERROR-CALLBACK and AUTHENTICATION-P."
  (with-local-quit
    (let ((uri           (->> query-map orgtrello-data-entity-uri (orgtrello-query--compute-url server)))
          (entity-method (orgtrello-data-entity-method query-map))
          (params        (when authentication-p (orgtrello-query--authentication-params)))
          (parser        'orgtrello-query--http-parse)
          (headers       '(("Content-type" . "application/json")))
          (data          (encode-coding-string (->> query-map orgtrello-data-entity-params json-encode) 'utf-8))
          (success-cbck  (if success-callback success-callback 'orgtrello-query--standard-success-callback))
          (error-cbck    (if error-callback error-callback 'orgtrello-query--standard-error-callback)))
      (if (orgtrello-data-entity-sync query-map)
          (request uri
                   :sync    t
                   :type    entity-method
                   :params  params
                   :headers headers
                   :data    data
                   :parser  parser
                   :success success-cbck
                   :error   error-cbck)
        `(deferred:$
           (request-deferred ,uri
                             :type    ,entity-method
                             :params  (quote ,params)
                             :headers (quote ,headers)
                             :data    ,data
                             :parser  (quote ,parser))
           (deferred:nextc it
             ,success-cbck)
           (deferred:error it
             ,error-cbck))))))
```

Can you please try and apply this to your local install and check whether you still see your error after that?

Install: <kbd>M-: <paste-snippet> RET</kbd>

Thanks

Cheers,

**Comment by ardumont** [comment] 2018-03-11 08:00
As in #379, should be fixed in 0.8.1.

**Comment by ow-clare** [comment] 2018-03-12 09:08
@ardumont  

it's fixed , I can update my trello dashboard with emacs,
 
Many many thanks,

**Comment by ardumont** [comment] 2018-03-12 10:05
> it's fixed , I can update my trello dashboard with emacs,

Awesome!

> Many many thanks,

Well, thanks for raising this up and thanks @PierreTechoueyres \m/

**Closed** 2018-03-12 10:05 UTC
Labels: need-feedback
