### ISSUE TITLE
Sync fails, complains hash-table size

### ISSUE THREAD

**Issue by skallinen** [org-trello/org-trello#392] opened 2019-01-19 12:21 UTC
Hello,

## bug?
Sync fails with this error
```org-trello - Sync trello board ’Tasks’ to buffer ’kanban.org’... FAILED. Error: (wrong-type-argument sequencep #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
org-trello - Opened trello-cards: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ())
```

### M-x org-trello-bug-report
System information:
```- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.1)
 of 2018-12-25
- org version: 8.2.10
- org-trello version: 0.8.0
- org-trello path: /home/sakalli/.emacs.d/elpa/org-trello-20180331.631/org-trello.el
- request-backend: curl
- kill-whole-line: nil
user-error: Minibuffer window is not active
mwheel-scroll: End of buffer
```

### Expected behavior

prefix + org-trello-sync-buffer
### Actal behavior
Sync failed and threw errors

Any ideas how to fix?

**Comment by skallinen** [comment] 2019-01-19 12:32
nevermind... seems to work now... not sure what th problem was.

**Comment by qleguennec** [comment] 2019-03-13 10:59
Facing the same issue.

**Comment by ardumont** [comment] 2019-03-13 12:37
@skallinen @qleguennec Does `M-x org-trello-check-setup` say something?

Also, how did you install org-trello?

**Comment by qleguennec** [comment] 2019-03-13 19:50
@ardumont I installed org-trello via `straight/melpa`.
Here is the output of `org-trello-check-setup`:
```
org-trello - Checking setup.
org-trello - Checking setup....
Loading /home/void/.emacs.d/.trello/quentinleguennec2.el (source)...done
org-trello - Checking trello connection...
org-trello - Checking setup. DONE.
org-trello - Account quentinleguennec2 configured! Everything is ok!
```

When I run `C-u M-x org-trello-sync-buffer`, I have that error:
```
sations.org’...
org-trello - client - Problem during request - error-thrown: (error http 403)
org-trello - Sync trello board ’REALISATIONS 2019’ to buffer ’realisations.org’... FAILED. Error: (wrong-type-argument sequencep #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
```
It seems to happen when the board has many cards, as I don't have the issue in a smaller one.

**Comment by qleguennec** [comment] 2019-03-13 19:52
Actually, I just realized #385 might be more related.

**Comment by ardumont** [comment] 2019-07-10 12:42
As mentioned, closing because most probably a duplicate of #385 (which is more developed).

Thanks

**Closed by ardumont** 2019-07-10 12:42 UTC
Labels: duplicate
